CREATE TABLE IF NOT EXISTS game(
    id SERIAL PRIMARY KEY ,
    status VARCHAR(150) NOT NULL,
    player1 VARCHAR(150) NOT NULL,
    player2 VARCHAR(150) NOT NULL,
    winner VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS moves(
    id SERIAL PRIMARY KEY,
    game_id INTEGER REFERENCES game(id),
    player_color VARCHAR(10) NOT NULL,
    piece VARCHAR(10) NOT NULL,
    from_x INTEGER NOT NULL,
    from_y INTEGER NOT NULL,
    to_x INTEGER NOT NULL,
    to_y INTEGER NOT NULL,
    move_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL
);
